### ISSUE TITLE
How to check the quality and collection rate of the stream？

### ISSUE THREAD

**Issue by whxq** [risingfbk/p4ddle#4] opened 2024-07-09 12:56 UTC
Dear author, I would like to ask how do you test the traffic collection efficiency and sFNR of Bloomfilter.

**Comment by luisdknob** [comment] 2024-07-09 13:09
Hello @whxq, I do not know if I understood your question correctly, so if my answer does not make sense to you, let me know. 

We used the log console option (on the bmv2) to validate the packets that cross the p4 switch and compare the results with those from P4ddle. 

Since we reproduced a pcap with tcpreplay, we also validated the number of packets transferred during the experiment with the pcap stats.

**Comment by luisdknob** [comment] 2024-07-09 13:11
Adding on more thing:

You can check the log message in the p4 files
`log_msg("log_flow: {},{},{},{},{},{}",{meta.srcAddr,meta.srcPort, meta.dstAddr, meta.dstPort, meta.ipProtocol, rc});`

**Comment by whxq** [comment] 2024-07-09 14:19
Hello, thank you for your answer. But I did not see a log file for P4 after following the steps you provided to create the topology. Is sim.py used to simulate traffic to detect the quality of Bloom filter collected streams?

**Comment by luisdknob** [comment] 2024-07-10 07:46
> Hello, thank you for your answer. But I did not see a log file for P4 after following the steps you provided to create the topology. Is sim.py used to simulate traffic to detect the quality of Bloom filter collected streams?

Hello, the p4 switch log is usually saved in the /tmp folder. You can also find some of the files that we used to run the experiments in the branch v1-experiments.

Regarding sim.py, it was used to simulate scenarios with distinct flow sizes, number of flows, and characteristics. Still, it is all synthetic and will not generate real flows that could be added to the mininet/bmv2. More information about the simulation can be found in the paper.

**Comment by whxq** [comment] 2024-07-10 14:37
8/5000
Thank you very much for your answer！

**Comment by whxq** [comment] 2024-07-10 14:38
Thank you very much for your answer！

**Comment by luisdknob** [comment] 2024-07-11 06:15
I'm closing the issue. If you need any other info, you can reopen it.

**Closed as completed by luisdknob** 2024-07-11 06:15 UTC
